# Common env var defaults for all job scripts.
# Sourced (not executed), so variables are set in the caller's scope.

PARENT_MODEL=${PARENT_MODEL:-ACCESS-OM2-1}
VELOCITY_SOURCE=${VELOCITY_SOURCE:-cgridtransports}
W_FORMULATION=${W_FORMULATION:-wdiagnosed}
ADVECTION_SCHEME=${ADVECTION_SCHEME:-centered2}
TIMESTEPPER=${TIMESTEPPER:-AB2}
TRACE_SOLVER_HISTORY=${TRACE_SOLVER_HISTORY:-no}
AA_M=${AA_M:-40}
NLSAA_BETA=${NLSAA_BETA:-1.0}
SMAA_SIGMA_MIN=${SMAA_SIGMA_MIN:-0.0}
SMAA_STABILIZE=${SMAA_STABILIZE:-no}
SMAA_CHECK_OBJ=${SMAA_CHECK_OBJ:-no}
SMAA_ORDERS=${SMAA_ORDERS:-332}
LINEAR_SOLVER=${LINEAR_SOLVER:-Pardiso}
LUMP_AND_SPRAY=${LUMP_AND_SPRAY:-no}
MATRIX_PROCESSING=${MATRIX_PROCESSING:-raw}
INITIAL_AGE=${INITIAL_AGE:-TMage}
TM_SOURCE=${TM_SOURCE:-avg24}
MODEL_CONFIG="${VELOCITY_SOURCE}_${W_FORMULATION}_${ADVECTION_SCHEME}_${TIMESTEPPER}"
export PARENT_MODEL VELOCITY_SOURCE W_FORMULATION ADVECTION_SCHEME TIMESTEPPER TRACE_SOLVER_HISTORY
export AA_M NLSAA_BETA SMAA_SIGMA_MIN SMAA_STABILIZE SMAA_CHECK_OBJ SMAA_ORDERS
export LINEAR_SOLVER LUMP_AND_SPRAY MATRIX_PROCESSING INITIAL_AGE TM_SOURCE

echo "PARENT_MODEL=$PARENT_MODEL"
echo "VELOCITY_SOURCE=$VELOCITY_SOURCE"
echo "W_FORMULATION=$W_FORMULATION"
echo "ADVECTION_SCHEME=$ADVECTION_SCHEME"
echo "TIMESTEPPER=$TIMESTEPPER"
echo "TRACE_SOLVER_HISTORY=$TRACE_SOLVER_HISTORY"
echo "AA_M=$AA_M"
echo "NLSAA_BETA=$NLSAA_BETA"
echo "SMAA_SIGMA_MIN=$SMAA_SIGMA_MIN"
echo "SMAA_STABILIZE=$SMAA_STABILIZE"
echo "SMAA_CHECK_OBJ=$SMAA_CHECK_OBJ"
echo "SMAA_ORDERS=$SMAA_ORDERS"
echo "LINEAR_SOLVER=$LINEAR_SOLVER"
echo "LUMP_AND_SPRAY=$LUMP_AND_SPRAY"
echo "MATRIX_PROCESSING=$MATRIX_PROCESSING"
echo "INITIAL_AGE=$INITIAL_AGE"
echo "TM_SOURCE=$TM_SOURCE"
echo "MODEL_CONFIG=$MODEL_CONFIG"

# Bounds checking: set CHECK_BOUNDS=yes to run julia with --check-bounds=yes
CHECK_BOUNDS=${CHECK_BOUNDS:-no}
JULIA_BOUNDS_FLAG=""
if [ "$CHECK_BOUNDS" = "yes" ]; then
    JULIA_BOUNDS_FLAG="--check-bounds=yes"
    echo "CHECK_BOUNDS=yes (running julia with --check-bounds=yes)"
fi
